version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - joshuapbritz
  assignees:
  - joshuapbritz
  labels:
  - enhancement
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.1
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
    - 7.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: rollup-plugin-preserve-shebang
    versions:
    - 1.0.1
  - dependency-name: minimist
    versions:
    - 1.2.5
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.24.3
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
